enum ProLocDetailsActionTypeKey {

    GET_PRO_LOC_DETAILS_DATA= "GET_PRO_LOC_DETAILS_DATA",
    GET_PRO_LOC_DETAILS_DATA_SUCCESS= "GET_PRO_LOC_DETAILS_DATA_SUCCESS",
    GET_PRO_LOC_DETAILS_DATA_SPINNER= "GET_PRO_LOC_DETAILS_DATA_SPINNER",
    GET_PRO_LOC_DETAILS_DATA_API_ERROR= "GET_PRO_LOC_DETAILS_DATA_API_ERROR",
    FILTER_MODAL_VISIBLE_STATUS = "FILTER_MODAL_VISIBLE_STATUS",
    GET_PRO_LOC_RESERVATION_DATA = "GET_PRO_LOC_RESERVATION_DATA",
    GET_PRO_LOC_RESERVATION_DATA_SUCCESS = "GET_PRO_LOC_RESERVATION_DATA_SUCCESS",
}

export default ProLocDetailsActionTypeKey;