enum PropertiesActionTypeKey {

    GET_PROPERTIES_DATA= "GET_PROPERTIES_DATA",
    GET_PROPERTIES_DATA_SUCCESS= "GET_PROPERTIES_DATA_SUCCESS",
    GET_PROPERTIES_DATA_SPINNER= "GET_PROPERTIES_DATA_SPINNER",
    GET_PROPERTIES_DATA_API_ERROR= "GET_PROPERTIES_DATA_API_ERROR"
}

export default PropertiesActionTypeKey;