server.port: 8080
portal:
   dataSource:
      url: 
      userName: 
      password: 
      driver: 

xyz:
   property-events:
      datasource:
         url: 
         username: 
         password: 
         driver: 
         showSql: 
