enum LocationActionTypeKey {

    GET_LOCATIONS_DATA= "GET_LOCATIONS_DATA",
    GET_LOCATIONS_DATA_SUCCESS= "GET_LOCATIONS_DATA_SUCCESS",
    GET_LOCATIONS_DATA_SPINNER= "GET_LOCATIONS_DATA_SPINNER",
    GET_LOCATIONS_DATA_API_ERROR= "GET_LOCATIONS_DATA_API_ERROR"
}

export default LocationActionTypeKey;