enum MainModelActionTypeKey {
    LOAD_INITIAL_MAIN_MODEL = 'LOAD_INITIAL_MAIN_MODEL',
    MAIN_MODEL_LOAD_SUCCESS = 'MAIN_MODEL_LOAD_SUCCESS',
    LOAD_DIRTY_FLAG = 'LOAD_DIRTY_FLAG',
    LOAD_SETTING_DIRTY_FLAG = 'LOAD_SETTING_DIRTY_FLAG'
}

export default MainModelActionTypeKey;