import { LocaleMap } from '@unifocus/js-utils';

/**
 * WARNING: This file is auto-generated from the bundle-localization tool. Do not edit this file directly.
 *
 * This file contains resource strings used by the @unifocus/js-utils formatMessage function.
 */
const messages: LocaleMap = {
   "en": {}
};

export default messages;
